[tasks.one]
command = "printf"
args = ["1,"]

[tasks.two]
command = "printf"
args = ["2,"]

[tasks.done]
command = "printf"
args = [",done\n"]

[tasks.both]
serial_tasks = ["one", "two"]

[tasks.both_at_the_same_time]
parallel_tasks = ["one", "two"]

[tasks.env_example]
command = "sh"
args = ["-c", "echo FOO=$FOO"]
env = { FOO = "BAR" }

[tasks.hidden]
command = "echo"
args = ["I am sneaky"]
hide = true

[tasks.shell]
shell_script = '''
VAR="World"
echo Hello ${VAR}!
'''

[tasks.serial_wide]
serial_tasks = [
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "done",
]

[tasks.parallel_wide]
parallel_tasks = [
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "one",
  "two",
  "done",
]

[tasks.shell_wide]
shell_script = '''
echo '1...2...3...4...5...6...7...8...9...10...11...12...13...14...15...16...17...18...19...20...21...22...23...24...25...26...27...28...29...30...31...32...33...34...35...36...37...38...39...40...41...42...43...44...45...46...47...48...49...50!'
'''

[tasks.shell_wide_multibyte]
shell_script = '''
echo '🥹😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇😇🤣'
'''

[tasks.shell_5_tall]
shell_script = '''
echo 1
echo 2
echo 3
echo 4
echo 5
'''

[tasks.shell_6_tall]
shell_script = '''
echo 1
echo 2
echo 3
echo 4
echo 5
echo 6
'''

[tasks.shell_very_tall]
shell_script = '''
echo 1
echo 2
echo 3
echo 4
echo 5
echo 6
echo 7
echo 8
echo 9
echo 10
echo 11
echo 12
echo 13
echo 14
echo 15
echo 16
echo 17
echo 18
echo 19
echo 20
echo 21
echo 22
echo 23
echo 24
echo 25
echo 26
echo 27
echo 28
echo 29
echo 30
echo 31
echo 32
echo 33
echo 34
echo 35
echo 37
echo 38
echo 39
echo 40
echo 41
echo 42
echo 43
echo 44
echo 45
echo 46
echo 47
echo 48
echo 49
echo 50
echo 51
echo 52
echo 53
echo 54
echo 55
echo 56
echo 57
echo 58
echo 59
echo 60
echo 61
echo 62
echo 63
echo 64
echo 65
'''
